//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PFW_CW1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class causes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public causes()
        {
            this.pledges = new HashSet<pledges>();
        }
    
        public int causeId { get; set; }
        public string author { get; set; }
        public string title { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public int status { get; set; }
        public string description { get; set; }
        public string photoLnk { get; set; }
    
        public virtual members members { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pledges> pledges { get; set; }
    }
}
